- Important:
    - My Website:
        - icon: mdi-star-box
          href: https://goshsamit.com
    - My Github:
        - icon: si-github
          href: https://github.com/goshSAMit/

- Reference:
    - Homepage:
        - icon: si-homepage
          href: https://gethomepage.dev/
    - Homepage Dashboard Icons:
        - icon: si-homepage
          href: https://github.com/homarr-labs/dashboard-icons
    - Material Design Icons:
        - icon: mdi-alpha-m
          href: https://pictogrammers.com/library/mdi/
    - Simple Icons:
        - icon: mdi-alpha-s
          href: https://simpleicons.org/
