- Virtualization:
    - Proxmox:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        description: Homelab Proxmox Server

- Networking:
    - PFSense:
        icon: pfsense.svg
        href: "{{HOMEPAGE_VAR_PFSENSE_URL}}"
        description: Gateway and Firewall
    - Pi-Hole:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE_URL_ADMIN}}"
        description: Pi-Hole
    - Traefik:
        icon: traefik-proxy.svg
        href: "{{HOMEPAGE_VAR_TRAEFIK_URL}}"
        description: Traefik Proxy for Production Cert Management
    - TP-Link Main Switch:
        icon: tp-link.svg
        href: "{{HOMEPAGE_VAR_SWITCH_URL}}"
        description: Main 24-port PoE switch

- Group A:
    - Service A:
        href: http://localhost/

- Group B:
    - Service B:
        href: http://localhost/